export const USER_ROLES = {
  ADMIN: 'ADMIN',
  CONSERVATIONIST: 'CONSERVATIONIST',
  RESEARCHER: 'RESEARCHER'
} as const

export const ACTIVITY_TYPES = {
  PATROL: 'PATROL',
  WILDLIFE_SIGHTING: 'WILDLIFE_SIGHTING',
  ILLEGAL_ACTIVITY: 'ILLEGAL_ACTIVITY',
  FOREST_FIRE: 'FOREST_FIRE',
  RESCUE_OPERATION: 'RESCUE_OPERATION',
  RESEARCH_SURVEY: 'RESEARCH_SURVEY',
  AWARENESS_PROGRAM: 'AWARENESS_PROGRAM'
} as const

export const CONSERVATION_STATUS = {
  CRITICALLY_ENDANGERED: 'CRITICALLY_ENDANGERED',
  ENDANGERED: 'ENDANGERED',
  VULNERABLE: 'VULNERABLE',
  NEAR_THREATENED: 'NEAR_THREATENED',
  LEAST_CONCERN: 'LEAST_CONCERN',
  DATA_DEFICIENT: 'DATA_DEFICIENT'
} as const

export const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED'
} as const

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500
} as const